language: node_js
node_js:
  - "7"
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "s3://cell5.co.uk/"
  skip_cleanup: true
  region: "eu-west-1"
  local_dir: build
  cache_control: "max-age=604800"
