version: '2'
services:
  app:
    build: .
    container_name: cell5site
    image: node_bower_gulp:dev
    command: npm start
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"